import os
from dotenv import load_dotenv
import streamlit as st

from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.chains import RetrievalQA

# Load local environment variables from .env (kept out of git)
load_dotenv()

# Fail fast with a clear UI message if the API key is missing
api_key = os.getenv("OPENAI_API_KEY", "").strip()
if not api_key:
    st.error("OPENAI_API_KEY not set. Copy .env.example to .env and add your key.")
    st.stop()

st.title("Enterprise Support Copilot")

# Set user expectations for grounded answers
st.caption(
    "This Copilot answers questions using only the documents in ./docs. "
    "If the answer is not in the knowledge base, it will respond that it does not know."
)

# Embeddings model used to index and query your documentation
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

# Vector store is generated by ingest.py and stored locally (not committed)
if not os.path.exists("vector_db"):
    st.warning("Vector store not found. Run: make ingest or python ingest.py")
    st.stop()

# Loading FAISS uses pickle for metadata, so only load stores you created locally
vectorstore = FAISS.load_local(
    "vector_db",
    embeddings,
    allow_dangerous_deserialization=True
)

# MMR reduces redundant retrieval and helps keep citations tight
# k controls how many chunks are returned to the LLM
retriever = vectorstore.as_retriever(
    search_type="mmr",
    search_kwargs={"k": 1, "fetch_k": 6}
)

# RetrievalQA wires retrieval + generation and can return source docs for citations
qa = RetrievalQA.from_chain_type(
    llm=ChatOpenAI(model="gpt-4o-mini", temperature=0.2),
    retriever=retriever,
    return_source_documents=True
)

query = st.text_input("Ask a question about company IT or HR systems")

if query:
    # Call the chain in dict mode so we get both the answer and the source docs
    result = qa({"query": query})

    # Primary response shown to the user
    st.write(result["result"])

    # Show which doc files were used for grounding
    with st.expander("Sources"):
        seen = set()
        for doc in result["source_documents"]:
            src = doc.metadata.get("source", "unknown")
            if src not in seen:
                st.write(src)
                seen.add(src)